books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name="books"
urlpatterns = [

    path('',views.home,name='home'),
    path('add',views.add,name='add'),
    path('view',views.view,name='view'),
    path('search',views.searchbooks,name='search'),
    path('details/<int:p>',views.details,name='details'),
    path('edit/<int:p>',views.edit,name='edit'),
    path('delete/<int:p>',views.delete,name='delete'),
]

library/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('users/',include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
app_name="users"

urlpatterns = [
    path('reg',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('viewusers',views.viewusers,name='viewusers'),
]

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    pages=models.IntegerField()
    price=models.IntegerField()
    language=models.CharField(max_length=20)
    cover=models.ImageField(upload_to="images")
    pdf=models.FileField(upload_to="pdf")


    def __str__(self):
         return self.title


users/models.py

from django.db import models

# Create your models here.
class Users(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place=models.CharField(max_length=20)
    number=models.IntegerField()
    gender=models.CharField(max_length=20)

    def __str__(self):
        return self.name

books/views.py
from django.shortcuts import render
from books.models import Book
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
    return render(request,'home.html')

@login_required
def add(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        l = request.POST['l']
        pa = request.POST['pa']

        c = request.FILES.get('c')
        f = request.FILES.get('f')
        b=Book.objects.create(title=t,author=a,price=p,pages=pa,language=l,cover=c,pdf=f)
        b.save()
        return view(request)
    return render(request,'add.html')

@login_required
def view(request):
    k=Book.objects.all()
    return render(request,'view.html',{'book':k})

@login_required
def details(request,p):
    k=Book.objects.get(id=p)
    return render(request,'details.html',{'book':k})

@login_required
def edit(request,p):
    k = Book.objects.get(id=p)
    if(request.method=="POST"):
        k.title=request.POST['t']
        k.author=request.POST['a']
        k.price=request.POST['p']
        k.pages=request.POST['pa']
        k.language=request.POST['l']
        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.cover=request.FILES.get('i')

        if(request.FILES.get('f') == None):
            k.save()
        else:
            k.pdf = request.FILES.get('f')
        k.save()
        return view(request)

    return render(request,'edit.html',{'book':k})

@login_required()
def delete(request,p):
    k=Book.objects.get(id=p)
    k.delete()
    return view(request)


from django.db.models import Q

def searchbooks(request):
    k=None                         #initialize k as None(no value)
    if(request.method=="POST"):
        query=request.POST['q']    #get input key from form
        if query:
            k=Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))    #it checks the key in title and author field.
            #filter funtion returns only the matching records., icontains-->anywhere inside the field,   i--->caseinsensive{uppercase and lower case select}
    return render(request,'search.html',{'search':k})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from users.models import Users
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
# Create your views here.

@login_required
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        f = request.POST['f']
        l = request.POST['l']
        e = request.POST['e']

        if(p==cp):
            u=User.objects.create_user(username=u,password=p,first_name=f,last_name=l,email=e)
            u.save()
        else:
            return HttpResponse("Password are not same")
        return redirect('users:login')

    return render(request,'register.html',)
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("invalid")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('books:home')

@login_required
def viewusers(request):
    k = Users.objects.all()
    return render(request,'viewusers.html',{'users':k})

templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 >Add Book</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="Enter The Title">
</div>

    <div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Enter The Author">
</div>

    <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="Enter The Price">
</div>

    <div class="mb-3">
  <label class="form-label">Pages</label>
  <input type="number" class="form-control" name="pa" placeholder="Enter The Pages">
</div>

    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" placeholder="Enter The Language">
</div>

    <div class="mb-3">
  <label class="form-label">Cover</label>
  <input type="file" class="form-control" name="c">
</div>

    <div class="mb-3">
  <label class="form-label">Pdf</label>
  <input type="file" class="form-control" name="f">
</div>

    <div class="mb-3">

  <input type="submit" value="ADD">
</div>
</form>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto  mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'books:home' %}">Home</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:add' %}">Add Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'books:view' %}">View Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{%url 'users:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="{%url 'users:register' %}" >Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{%url 'users:login' %}" >Login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link " href="{%url 'users:viewusers' %}">Viewusers</a>
        </li>
        {% endif %}
      </ul>
      <form method="POST" class="d-flex" style="margin-left:200px;" action="{% url 'books:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
<h2>view details</h2>

<div class="card mx-auto mb-3 bg-info " style="max-width: 600px;">
  <div class="row g-0">
    <div class="col-md-4 me-5">
      <img src="{{book.cover.url}}" class="img-fluid rounded-start p-3" height="200px" width="100%" alt="...">
    </div>
    <div class="col-md-7 mt-5">
      <div class="card-body">
        <h5 class="card-title m-2">Title:{{book.title}}</h5>
        <h5 class="card-text m-2">Author:{{book.author}}</h5>
        <h5 class="card-text m-2">Language:{{book.language}}</h5>
        <h6 class="card-text m-2">Price:{{book.price}}</h6>
        <a href="{{book.pdf.url}}" class="btn btn-danger mt-5">Download</a>
      </div>
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 >Add Book</h2>
<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" value="{{book.title}}" placeholder="Enter The Title">
</div>

    <div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="Enter The Author">
</div>

    <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" value="{{book.price}}" placeholder="Enter The Price">
</div>

    <div class="mb-3">
  <label class="form-label">Pages</label>
  <input type="number" class="form-control" name="pa" value="{{book.pages}}" placeholder="Enter The Pages">
</div>

    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}" placeholder="Enter The Language">
</div>

    <div class="mb-3">
  <label class="form-label">Cover</label>
        <img src = "{{book.cover.url}}" >
  <input type="file" class="form-control" name="i" >
</div>

    <div class="mb-3">
  <label class="form-label">Pdf</label>
        <a href="{{book.pdf.url}}">Pdf</a>
  <input type="file" class="form-control" name="f">
</div>

    <div class="mb-3">

  <input type="submit" value="ADD">
</div>
</form>



{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center text-primary mt-3">Welcome Library Home<span>

{% if user.is_authenticated %}
{{user.username}}
{% else %}
guest </span></h2>

{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center text-primary mt-3">Welcome to Login</h2>


<form method="POST">

{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">UserName</label>
  <input type="text" class="form-control" name="u" placeholder="Enter The UserName">
</div>

    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter The Password">
</div>
    <div class="mb-3">

  <input type="submit" value="SUBMIT">
    </div>

</form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center text-primary mt-3">Welcome to Register</h2>

<form method="POST" enctype="multipart/form-data">

{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">UserName</label>
  <input type="text" class="form-control" name="u" placeholder="Enter The UserName">
</div>

    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter The Password">
</div>

    <div class="mb-3">
  <label class="form-label">Conform Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter The Conform Password">
</div>

    <div class="mb-3">
  <label class="form-label">First Name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter The First Name">
</div>

    <div class="mb-3">
  <label class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter The Last Name">
</div>

    <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter The Email">
</div>

    <div class="mb-3">

  <input type="submit" value="SUBMIT">
</div>
</form>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 >search Book</h2>
{{ book }}
<table class="table table-bordered bg-primary">

<!--#### TABLE ####-->

<!--<table class="table table-boarded bg-light">-->
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PAGES</th>
        <th>PRICE</th>
        <th>LANGUAGE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
        {% for i in book %}
    <tr>
        <td><img src="{{i.cover.url}}" height="150px" width="150px" ></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.pages}}</td>
        <td>{{i.price}}</td>
        <td>{{i.language}}</td>
        <td><a href="{{i.pdf.url}}" class="btn btn-light">Download</a></td>

    </tr>
    {% endfor %}

</table>

{% endblock %}

templates/view.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<h2 class="text-center text-primary mt-3">Welcome to View Books</h2>

<table class="table table-bordered bg-primary">

<!--#### TABLE ####-->

<!--<table class="table table-boarded bg-light">-->
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PAGES</th>
        <th>PRICE</th>
        <th>LANGUAGE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
        {% for i in book %}
    <tr>
        <td><img src="{{i.cover.url}}" height="150px" width="150px" ></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.pages}}</td>
        <td>{{i.price}}</td>
        <td>{{i.language}}</td>
        <td><a href="{{i.pdf.url}}" class="btn btn-light">Download</a></td>
        <td><a href="{% url 'books:details' i.id %}" class="btn btn-danger">view</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-danger">Edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}

</table>

<!--#### LIST ####-->

<!-- <ol>-->

<!--    {% for i in book %}-->

<!--        <li>Book Details</li>-->
<!--        <ul style="list-style-type:disc;">-->
<!--        <li/>title : {{i.title}}-->
<!--        <li/>author : {{i.author}}-->
<!--        <li/>pages : {{i.pages}}-->
<!--        <li/>price : {{i.price}}-->
<!--        <li/>language : {{i.language}} </ul>-->

<!--    {% endfor %}-->
<!-- </ol>-->

<!--{{book}}-->
{% endblock %}

templates/viewusers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2 class="text-center text-primary mt-3">Welcome to View users</h2>



<!--#### TABLE ####-->

<table class="table table-boarded bg-light">
    <tr>
        <th>NAME</th>
        <th>AGE</th>
        <th>PLACE</th>
        <th>NUMBER</th>
        <th>GENDER</th>
    </tr>
    <tr>
        {% for i in users %}
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.place}}</td>
        <td>{{i.number}}</td>
        <td>{{i.gender}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}